package our.company.name.loan.designed.ui.implementations;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import our.company.name.loan.application.custom.ui.TotalLoanHLayout;
import our.company.name.loan.application.custom.ui.components.LoanMenuBar;
import our.company.name.loan.application.enums.PaymentMethod;
import our.company.name.loan.designed.ui.interfaces.INavigate;

import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class HomePage extends CustomComponent implements View, INavigate {

	// aditya.rajurkar@gmail.com

	private VerticalLayout mainLayout;
	private LoanMenuBar menuBar;
	private TotalLoanHLayout totalLoanHLayout;

	/** Class variables (other than UI-Components) Declaration (START) */
	static Logger log = LoggerFactory.getLogger(HomePage.class);

	public static final String NAME = "home";

	/** Class variables (other than UI-Components) Declaration (END) */



	/** UI - Components Declaration (END) */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the Vaadin
	 * visual editor.
	 */
	public HomePage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		addAllButtonClickListeners();

	}

	@Override
	public void enter(ViewChangeEvent event) {

	}

	@Override
	public void navigateTo(String vaadinPageName) {
		getUI().getNavigator().navigateTo(vaadinPageName);
	}

	@Override
	public void addAllButtonClickListeners() {


			/**
			 * The user wants to "Logout" of his / her session. Perform all the
			 * 'clean-up' actions and deallocating of resources (if any) here in
			 * this method.
			 * */
		/*
		 * @Override public void buttonClick(ClickEvent event) {
		 * 
		 * wrappedSession.removeAttribute(USER_ATTRIBUTE_NAME);
		 * 
		 * Set<String> attributeNames = wrappedSession.getAttributeNames();
		 * 
		 * WrappedSessionDiagnostics.printSetInformation(attributeNames);
		 * 
		 * // Navigate again to Login Page navigateTo(LoginView.NAME);
		 * 
		 * } });
		 */
	}

	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// menuBar
		menuBar = new LoanMenuBar();
		menuBar.setImmediate(false);
		menuBar.setWidth("-1px");
		menuBar.setHeight("-1px");
		mainLayout.addComponent(menuBar);
		
		// totalLoanHLayout
		
		totalLoanHLayout = new TotalLoanHLayout(PaymentMethod.CHEQUE);
		mainLayout.addComponent(totalLoanHLayout);

		return mainLayout;
	}

}
