CREATE DATABASE IF NOT EXISTS accounting;

USE accounting;

CREATE TABLE IF NOT EXISTS `user` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Firstname` varchar(30) DEFAULT NULL,
  `Lastname` varchar(30) DEFAULT NULL,
  `Mobile` varchar(15) DEFAULT NULL,
  `Email` varchar(30) DEFAULT NULL,
  `Password` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`Id`) 
) ENGINE=InnoDB AUTO_INCREMENT=1  DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS  RESIDENCE_TABLE
     (RESIDENCE_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, RESIDENCE_TYPE varchar(30) NOT NULL) 
		ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS  PRODUCT_TABLE (PRODUCT_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, VEHICLE_COMPANY varchar(50),VEHICLE_MODEL varchar(50))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS  CUSTOMER_TABLE 
                        ( CUSTOMER_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, FIRST_NAME varchar(30),LAST_NAME varchar(30),RES_ADD varchar(300), OFFICE_ADD varchar(300), 
                             PERMANENT_ADD varchar(300), TELEPHONE varchar(15), MOBILE varchar(15), EMAIL varchar(100))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS  RESALE_PROD_TABLE ( RP_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, X_PRODUCT_ID int, REGISTRATION_NUM varchar(100), 
                FOREIGN KEY (X_PRODUCT_ID) REFERENCES PRODUCT_TABLE (PRODUCT_ID))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


CREATE TABLE IF NOT EXISTS  RESALE_TABLE ( RESALE_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, X_PURCHASER_ID int, X_GARENTOR_ID int, X_RP_ID int,
                                FOREIGN KEY (X_PURCHASER_ID) REFERENCES CUSTOMER_TABLE (CUSTOMER_ID),
                                FOREIGN KEY (X_GARENTOR_ID) REFERENCES CUSTOMER_TABLE (CUSTOMER_ID),
                                FOREIGN KEY (X_RP_ID) REFERENCES RESALE_PROD_TABLE (RP_ID))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


-- ------------------------------------------------------------------------------------------------------------


CREATE TABLE IF NOT EXISTS  REPAY_MODE_TABLE ( REPAY_MODE_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, REPAY_MODE varchar(20))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS  LOAN_TABLE ( LOAN_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, X_CUSTOMER_ID int, X_RP_ID int ,ASSET_VALUE int, LOAN_AMOUNT int, TENURE int, INSTALLMENT int, ROI int,
                    DISBURSMENT_DATE DATE, CHEQUE_NO varchar(10), REPAYMENT_START DATE,
                    FOREIGN KEY (X_CUSTOMER_ID) REFERENCES CUSTOMER_TABLE (CUSTOMER_ID))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;



CREATE TABLE IF NOT EXISTS  REPAYMENT_TABLE ( REPAY_ID int PRIMARY KEY NOT NULL AUTO_INCREMENT, X_LOAN_ID int, X_REPAY_MODE_ID int, CASH_RECEIPT_NO varchar(10), LOAN_ACCOUNT_NO varchar(10),
     CHEQUE_NO varchar(10), BANK_NAME VARCHAR (100), AMOUNT int, AMOUNT_REMAINING int, 
     FOREIGN KEY (X_LOAN_ID) REFERENCES LOAN_TABLE (LOAN_ID),
     FOREIGN KEY (X_REPAY_MODE_ID) REFERENCES REPAY_MODE_TABLE (REPAY_MODE_ID))
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;














-- DROP TABLE RESIDENCE_TABLE;
-- DROP TABLE PRODUCT_TABLE; 
-- DROP TABLE CUSTOMER_TABLE;
-- DROP TABLE RESALE_PROD_TABLE;
-- DROP TABLE RESALE_TABLE;

-- DROP TABLE REPAY_MODE_TABLE;
-- DROP TABLE LOAN_TABLE;
-- DROP TABLE REPAYMENT_TABLE;

-- DROP SCHEMA accounting;